### ISSUE TITLE
Initializing a Tracer without a valid transport should not succeed

### ISSUE THREAD

**Issue by blast-hardcheese** [lightstep/lightstep-tracer-java#137]
I missed that netty had been removed as a dependency in one of the bugfix releases; instead of seeing an exception on top-level Tracer initialization, I instead got a cryptic `ClassCastException` when trying to create a span:

```
java.lang.ClassCastException: com.lightstep.tracer.shared.NoopSpan$NoopSpanContext cannot be cast to com.lightstep.tracer.shared.SpanContext
        at com.lightstep.tracer.shared.SpanBuilder.addReference(SpanBuilder.java:60) ~[server-1.3.2-SNAPSHOT.jar:na]
        at com.lightstep.tracer.shared.SpanBuilder.asChildOf(SpanBuilder.java:46) ~[server-1.3.2-SNAPSHOT.jar:na]
        at com.lightstep.tracer.shared.SpanBuilder.asChildOf(SpanBuilder.java:54) ~[server-1.3.2-SNAPSHOT.jar:na]
```

I would have expected to have an exception thrown when trying to construct a top-level Tracer. Alternately, I should have been forced to construct a tracer and choose my transport mechanism of choice, similar to:

```
Tracer tracer = new com.lightstep.tracer.jre.JRETracer(
         new DefaultNettyClientFactory(),
         new com.lightstep.tracer.shared.Options.OptionsBuilder()
            .withAccessToken("{your_access_token}")
            .build()
);
```

**Comment by blast-hardcheese** [comment]
👍
