### ISSUE TITLE
Exceptions:  com.lightstep.tracer.shared.GrpcCollectorClientProvider could not be instantiated

### ISSUE THREAD

**Issue by etsangsplk** [lightstep/lightstep-tracer-java#171]
accesToken and serviceName is read from getEnv
```            Options options = new Options.OptionsBuilder()
                    .withAccessToken(accesstoken)
                    .withComponentName(serviceName)
                    .withVerbosity(verbosity)
                    .withMetaEventLogging(true)
                    .build();
            Tracer tracer = new JRETracer(options);
```

```Exception in thread "main" java.util.ServiceConfigurationError: com.lightstep.tracer.shared.CollectorClientProvider: Provider com.lightstep.tracer.shared.GrpcCollectorClientProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.lightstep.tracer.shared.CollectorClientProvider.load(CollectorClientProvider.java:42)
	at com.lightstep.tracer.shared.CollectorClientProvider.<clinit>(CollectorClientProvider.java:19)
	at com.lightstep.tracer.shared.AbstractTracer.<init>(AbstractTracer.java:156)
	at com.lightstep.tracer.jre.JRETracer.<init>(JRETracer.java:31)
	at com.splunk.catlog.service.external.tracing.LightStep.registerTracer(LightStep.java:54)
	at com.splunk.catlog.service.external.tracing.Tracer.getTracer(Tracer.java:31)
	at com.splunk.catalog.Main.runAsRestServer(Main.java:93)
	at com.splunk.catalog.Main.main(Main.java:75)
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 10 more
Caused by: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:60)
	at com.lightstep.tracer.shared.GrpcCollectorClientProvider.<init>(GrpcCollectorClientProvider.java:16)
	at com.lightstep.tracer.shared.GrpcCollectorClientProvider.<clinit>(GrpcCollectorClientProvider.java:8)
	... 16 more
```

**Comment by etsangsplk** [comment]
After adding packages.. there is error in Jetty ALPN/NPN error
```  
    compile('io.grpc:grpc-netty:1.4.0')
    compile('io.netty:netty-tcnative-boringssl-static:2.0.5.Final')
```

```Tracer initialization failed with exception=Jetty ALPN/NPN has not been properly configured.```

**Comment by etsangsplk** [comment]
Fixed..   Ended up fixed by incoporating netty-tcnative-boringssl-static from
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting
But also found this: 
https://medium.com/sourcebytes/jetty-alpn-npn-has-not-been-properly-configured-solution-418417ee6502
