### ISSUE TITLE
Protocol buffers over grpc not working.

### ISSUE THREAD

**Issue by arpit728** [lightstep/lightstep-tracer-java#229]
I'm using lightstep tracer with opentracing-sepcialagent. The issue is that currently there is no way to use protocol buffers over grpc, to address this I added dependencies of `tracer-grpc` in lightstep-tracer-jre bundle and supplied this as jar in `sa.tracer` argument to specialagent.

special-agent version : `1.5.8`

No logs are currently getting reported to lightstep satellite, I am able to see this error in the application.

```
o.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 426
invalid content-type: null
trailers: Metadata(:status=426,date=Fri, 21 Feb 2020 10:30:35 GMT,content-length=0,x-envoy-upstream-service-time=0,server=istio-envoy)
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at com.lightstep.tracer.grpc.CollectorServiceGrpc$CollectorServiceBlockingStub.report(CollectorServiceGrpc.java:128)
	at com.lightstep.tracer.shared.GrpcCollectorClient.report(GrpcCollectorClient.java:52)
	at com.lightstep.tracer.shared.AbstractTracer.sendReportWorker(AbstractTracer.java:534)
	at com.lightstep.tracer.shared.AbstractTracer.sendReport(AbstractTracer.java:475)
	at com.lightstep.tracer.jre.JRETracer.flushInternal(JRETracer.java:38)
	at com.lightstep.tracer.shared.AbstractTracer$ReportingLoop.run(AbstractTracer.java:258)
	at java.lang.Thread.run(Thread.java:748)
```

Currently which collector(grpc/http) to be used is determined by the 'priority' field in collector class, I think instead this it should be picked up based on some external config. I think picking this up based on param `ls.collector.protocol=grpc` would make lot of sense.

**Comment by carlosalberto** [comment]
Closing this issue on behalf of #224
