### ISSUE TITLE
Android tracer crashes jellybean

### ISSUE THREAD

**Issue by nicks** [lightstep/lightstep-tracer-java#42]
Here's the stack trace:

```
java.lang.NoClassDefFoundError: java.util.concurrent.ThreadLocalRandom
                                                     at com.lightstep.tracer.shared.AbstractTracer.generateGUID(AbstractTracer.java:587)
                                                     at com.lightstep.tracer.shared.AbstractTracer.<init>(AbstractTracer.java:151)
                                                     at com.lightstep.tracer.android.Tracer.<init>(Tracer.java:31)
```

Note that this class does not exist on Jellybean.

Even more concerning: there are standard lint checks that are supposed to catch this problem but it looks like the gradle config has linting errors turned off (https://github.com/lightstep/lightstep-tracer-java/blob/master/lightstep-tracer-android/build.gradle#L64)

**Comment by bensigelman** [comment]
@nicks this is (clearly) bad -- will look and try to address in the next 24h (and hopefully can enable the linting, too).

**Comment by bensigelman** [comment]
@nicks: @bcronin's fix also reenables the linting which was inadvertantly turned off ages ago, probably in dev (or something).

**Comment by bcronin** [comment]
@nicks, I pushed a new version v0.9.16 to bintray and Maven with the fix (usually takes a while for Maven to update).

https://bintray.com/lightstep/maven/lightstep-tracer-android/0.9.16
