### ISSUE TITLE
Tracer in Spring Cloud causes  IllegalArgumentException: Jetty ALPN/NPN has not been properly configured

### ISSUE THREAD

**Issue by malafeev** [lightstep/lightstep-tracer-java#92]
I added lightstep-tracer-jre to Spring Cloud application and get:
```
Exception in thread "grpc-default-executor-1" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:148)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:137)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:108)
	at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiatorByType(NettyChannelBuilder.java:321)
```

Problem that Spring Boot uses Tomcat by default (with own ssl native library).
Migration to Jetty is not a solution for most customers. 
Playing with classloader doesn't look acceptable also. 

There is another jar hell problem: Spring cloud comes with dependencies on Netty and Guava.
But versions are different than in Tracer.

Problem can be fixed by developing Tracer without gRPC. 
It would be great to use some REST client.
For example Apache HttpClient.
It will solve this hell with jars and ssl.

**Comment by malafeev** [comment]
looks like latest versions don't have this problem, at least I cannot reproduce it anymore.

**Comment by malafeev** [comment]
I found a way to reproduce:
https://github.com/malafeev/spring-cloud-opentracing

**Comment by carlosalberto** [comment]
Hey @mohit24694 

Have you tried using the OkHtto as the transport protocol? Probably it could help with the issue, as @malafeev mentioned. Let us know.

**Comment by mohit24694** [comment]
Thanks @carlosalberto it worked for me
