### ISSUE TITLE
Null pointer exception in unit testing when I try ti create Tracer object

### ISSUE THREAD

**Issue by Hesamedin** [lightstep/lightstep-tracer-java#97]
Hi,

I want to test Tracer object and this is my test class (for Android):
```
package com.test.tracing;

import com.test.passenger.BuildConfigHelper;
import com.test.passenger.tracing.GlobalTracer;
import com.lightstep.tracer.android.Tracer;
import com.lightstep.tracer.shared.Options;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.modules.junit4.PowerMockRunner;

import android.content.Context;
import android.test.mock.MockContext;

import java.net.MalformedURLException;

import static org.junit.Assert.assertNotNull;

@RunWith(PowerMockRunner.class)
public class GlobalTracerTest {

    private GlobalTracer mGlobalTracer;

    @Before
    public void setUp() throws Exception {
        Options options;
        try {
            options = new Options.OptionsBuilder()
                    .withAccessToken(BuildConfigHelper.LIGHTSTEP_ACCESS_TOKEN)
                    .withComponentName("Pax Grab Android")
                    .build();
        } catch (MalformedURLException e) {
            throw new RuntimeException("Open tracer not created");
        }
        assertNotNull(options);

        Context context = new MockContext();
        assertNotNull(context);

        Tracer tracer = new Tracer(context, options); // <=== NullPointerException
        mGlobalTracer = new GlobalTracer(tracer);
    }

    @Test
    public void startTracing() throws Exception {
        mGlobalTracer.startTracing();
        for (int i=0; i<100000; i++) {
            // wait few millis
        }
        mGlobalTracer.stopTracing();
    }
}
```

This is what log displays:
```
at com.test.passenger.tracing.GlobalTracerTest.setUp(GlobalTracerTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.
```

Any idea would be appreciated. Thanks.

**Comment by Hesamedin** [comment]
The problem seems is in the latest version of `lightstep tracer Android`. I downgraded the lib to `0.10.1` and my test passed.

**Comment by malafeev** [comment]
issue should be moved to https://github.com/lightstep/lightstep-tracer-android

**Comment by malafeev** [comment]
@tedsuo github cannot move the issue to android tracer. Just close now?
